[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"runtime",
]

[patch.crates-io]
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" } 
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" } 
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" } 
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" } 
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" } 
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" } 
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" } 