version: "3"

services:
  dev-chain:
    build: .
    image: local/kilt-collator
    command: ./target/release/kilt-collator --tmp --ws-port 9977 --port 30336 --parachain-id 200 --validator -- --chain spec.json
    ports:
      - 9944:9944
